export enum EValidationErrors {
  ERROR_MUST_NOT_BE_EMPTY = 'ERROR_MUST_NOT_BE_EMPTY',
  ERROR_INVALID_EMAIL = 'ERROR_INVALID_EMAIL',
  ERROR_INVALID_PASSWORD = 'ERROR_INVALID_PASSWORD',
  ERROR_INVALID_IBAN = 'ERROR_INVALID_IBAN',
  ERROR_INVALID_BIC = 'ERROR_INVALID_BIC',
  ERROR_INVALID_NUMBER = 'ERROR_INVALID_NUMBER',
  ERROR_INVALID_POSTAL_CODE = 'ERROR_INVALID_POSTAL_CODE',
  ERROR_MUST_BE_TRUE = 'ERROR_MUST_BE_TRUE',
  ERROR_PASSWORDS_NOT_MATCHING = 'ERROR_PASSWORDS_NOT_MATCHING',
  ERROR_ACCEPT_CONDITIONS = 'ERROR_ACCEPT_CONDITIONS',
  ERROR_ACCEPT_PRIVACY_POLICY = 'ERROR_ACCEPT_PRIVACY_POLICY',
  ERROR_INVALID_PHONE_NUMBER = 'ERROR_INVALID_PHONE_NUMBER',
  ERROR_INVALID_SALES_TAX_ID = 'ERROR_INVALID_SALES_TAX_ID',
  ERROR_CLOSING_AFTER_OPENING = 'ERROR_CLOSING_AFTER_OPENING',
  ERROR_MUST_HAVE_AT_LEAST_ONE = 'ERROR_MUST_HAVE_AT_LEAST_ONE',
  ERROR_FILE_SIZE_LIMIT_EXCEEDED = 'ERROR_FILE_SIZE_LIMIT_EXCEEDED',
  ERROR_MUST_READ_CONTRACT = 'ERROR_MUST_READ_CONTRACT',
  ERROR_MUST_SIGN_CONTRACT = 'ERROR_MUST_SIGN_CONTRACT',
  ERROR_MUST_CONTAIN_ONLY_NUMBERS_LETTERS = 'ERROR_MUST_CONTAIN_ONLY_NUMBERS_LETTERS',
  ERROR_MUST_CONTAIN_ONLY_NUMBERS_LETTERS_COMMAS_POINTS = 'ERROR_MUST_CONTAIN_ONLY_NUMBERS_LETTERS_COMMAS_POINTS',
  ERROR_MUST_CONTAIN_ONLY_NUMBERS_LETTERS_HYPHENS = 'ERROR_MUST_CONTAIN_ONLY_NUMBERS_LETTERS_HYPHENS',
  ERROR_MAX_WORDS_EXCEEDED = 'ERROR_MAX_WORDS_EXCEEDED',
  ERROR_MAX_LENGTH_EXCEEDED = 'ERROR_MAX_LENGTH_EXCEEDED',
  ERROR_WRONG_FILE_TYPE = 'ERROR_WRONG_FILE_TYPE',
  ERROR_MUST_BE_POSITIVE_DECIMAL_NUMBER = 'ERROR_MUST_BE_POSITIVE_DECIMAL_NUMBER',
  ERROR_MUST_BE_PERCENTAGE = 'ERROR_MUST_BE_PERCENTAGE',
  ERROR_INVALID_DOMAIN = 'ERROR_INVALID_DOMAIN',
  ERROR_MUST_BE_PERSONAL_EMAIL = 'ERROR_MUST_BE_PERSONAL_EMAIL',
  ERROR_INVALID_DATE = 'ERROR_INVALID_DATE',
}

export const withArguments = (
  message: EValidationErrors,
  args: { [key: string]: string | number }
) => {
  // message: ERROR_FILE_SIZE_LIMIT_EXCEEDED ; args: { min: 1, max: 10}
  // result: ERROR_FILE_SIZE_LIMIT_EXCEEDED@@min:1@@max:10'
  const argsString = Object.entries(args).reduce((acc, [key, value]) => {
    return `${acc}@@${key}:${value}`;
  }, '');
  return `${message}${argsString}`;
};
